<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="contextproperties" nsURI="http://www.example.org/contextproperties"
    nsPrefix="contextproperties">
  <eClassifiers xsi:type="ecore:EClass" name="ContextDependentProperties" eSuperTypes="../../tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyannotation" upperBound="-1"
        eType="#//PropertyAnnotation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" upperBound="-1"
        eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextdefinition" upperBound="-1"
        eType="#//ContextDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyAnnotation" eSuperTypes="../../tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextannotation" upperBound="-1"
        eType="#//ContextAnnotation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
        eType="#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotatedElement" lowerBound="1"
        eType="ecore:EClass ../../mdpa.laf.referencemodel/model/LAF.ecore#//AssessmentFact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextAnnotation" eSuperTypes="../../tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyvalue" lowerBound="1"
        upperBound="-1" eType="#//PropertyValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextdefinition" lowerBound="1"
        upperBound="-1" eType="#//ContextDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="../../tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyvalue" upperBound="-1"
        eType="#//PropertyValue" containment="true" eOpposite="#//PropertyValue/parentProperty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyValue" eSuperTypes="../../tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentProperty" lowerBound="1"
        eType="#//Property" eOpposite="#//Property/propertyvalue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextDefinition" eSuperTypes="../../tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextDependentProperties"
        upperBound="-1" eType="#//ContextDependentContextElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gdprElements" lowerBound="1"
        upperBound="-1" eType="#//GDPRContextElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextElement" abstract="true" interface="true"
      eSuperTypes="../../tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="negated" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextDependentContextElement" eSuperTypes="#//ContextElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contextDependentProperty"
        lowerBound="1" eType="#//PropertyAnnotation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GDPRContextElement" eSuperTypes="#//ContextElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gdprElement" lowerBound="1"
        eType="ecore:EClass ../../mdpa.laf.referencemodel/model/LAF.ecore#//AssessmentFact"/>
  </eClassifiers>
</ecore:EPackage>
