<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="contextproperties" nsURI="http://www.example.org/contextproperties"
    nsPrefix="contextproperties">
  <eClassifiers xsi:type="ecore:EClass" name="ScopeDependentAssessmentFacts" eSuperTypes="../../tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="safAnnotation" upperBound="-1"
        eType="#//SAFAnnotation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scopeDependentAssessmentFact"
        upperBound="-1" eType="#//ScopeDependentAssessmentFact" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope" upperBound="-1"
        eType="#//Scope" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SAFAnnotation" eSuperTypes="../../tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="scopeSet" upperBound="-1"
        eType="#//ScopeSet" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scopeDependentAssessmentFact"
        lowerBound="1" eType="#//ScopeDependentAssessmentFact"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotatedElement" lowerBound="1"
        eType="ecore:EClass ../../mdpa.laf.referencemodel/model/LAF.ecore#//AssessmentFact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScopeSet" eSuperTypes="../../tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        upperBound="-1" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope" lowerBound="1" upperBound="-1"
        eType="#//Scope"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScopeDependentAssessmentFact" eSuperTypes="../../tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" upperBound="-1"
        eType="#//Expression" containment="true" eOpposite="#//Expression/parentAssessmentFact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="../../tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentAssessmentFact" lowerBound="1"
        eType="#//ScopeDependentAssessmentFact" eOpposite="#//ScopeDependentAssessmentFact/expression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scope" eSuperTypes="../../tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressionDependentScopeElements"
        upperBound="-1" eType="#//ExpressionDependentScopeElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lafScopeElements" upperBound="-1"
        eType="#//LAFScopeElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScopeElement" abstract="true" interface="true"
      eSuperTypes="../../tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="negated" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2003/XMLType#//Boolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionDependentScopeElement" eSuperTypes="#//ScopeElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="safAnnotation" lowerBound="1"
        eType="#//SAFAnnotation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LAFScopeElement" eSuperTypes="#//ScopeElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lafElement" lowerBound="1"
        eType="ecore:EClass ../../mdpa.laf.referencemodel/model/LAF.ecore#//AssessmentFact"/>
  </eClassifiers>
</ecore:EPackage>
