#

pluginName = mdpa.gdpr.metamodel.contextproperties Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_ContextDependentProperties_type = Context Dependent Properties
_UI_PropertyAnnotation_type = Property Annotation
_UI_ContextAnnotation_type = Context Annotation
_UI_Property_type = Property
_UI_PropertyValue_type = Property Value
_UI_ContextDefinition_type = Context Definition
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_ContextDependentProperties_propertyannotation_feature = Propertyannotation
_UI_ContextDependentProperties_property_feature = Property
_UI_ContextDependentProperties_contextdefinition_feature = Contextdefinition
_UI_PropertyAnnotation_contextannotation_feature = Contextannotation
_UI_PropertyAnnotation_property_feature = Property
_UI_PropertyAnnotation_annotatedElement_feature = Annotated Element
_UI_ContextAnnotation_propertyvalue_feature = Propertyvalue
_UI_ContextAnnotation_contextdefinition_feature = Contextdefinition
_UI_Property_propertyvalue_feature = Propertyvalue
_UI_ContextDefinition_gdprElements_feature = Gdpr Elements
_UI_Unknown_feature = Unspecified

_UI_PropertyValue_parentProperty_feature = Parent Property
_UI_ContextDefinition_contextDependentProperties_feature = Context Dependent Properties
_UI_ContextElement_type = Context Element
_UI_ContextDependentContextElement_type = Context Dependent Context Element
_UI_GDPRContextElement_type = GDPR Context Element
_UI_ContextElement_negated_feature = Negated
_UI_ContextDependentContextElement_contextDependentProperty_feature = Context Dependent Property
_UI_GDPRContextElement_gdprElement_feature = Gdpr Element
_UI_ScopeDependentAssessmentFacts_type = Scope Dependent Assessment Facts
_UI_SAFAnnotation_type = SAF Annotation
_UI_ScopeSet_type = Scope Set
_UI_ScopeDependentAssessmentFact_type = Scope Dependent Assessment Fact
_UI_Expression_type = Expression
_UI_Scope_type = Scope
_UI_ScopeElement_type = Scope Element
_UI_ExpressionDependentScopeElement_type = Expression Dependent Scope Element
_UI_LAFScopeElement_type = LAF Scope Element
_UI_ScopeDependentAssessmentFacts_safAnnotation_feature = Saf Annotation
_UI_ScopeDependentAssessmentFacts_scopeDependentAssessmentFact_feature = Scope Dependent Assessment Fact
_UI_ScopeDependentAssessmentFacts_scope_feature = Scope
_UI_SAFAnnotation_scopeSet_feature = Scope Set
_UI_SAFAnnotation_scopeDependentAssessmentFact_feature = Scope Dependent Assessment Fact
_UI_SAFAnnotation_annotatedElement_feature = Annotated Element
_UI_ScopeSet_expression_feature = Expression
_UI_ScopeSet_scope_feature = Scope
_UI_ScopeDependentAssessmentFact_expression_feature = Expression
_UI_Expression_parentAssessmentFact_feature = Parent Assessment Fact
_UI_Scope_expressionDependentScopeElements_feature = Expression Dependent Scope Elements
_UI_Scope_lafScopeElements_feature = Laf Scope Elements
_UI_ScopeElement_negated_feature = Negated
_UI_ExpressionDependentScopeElement_safAnnotation_feature = Saf Annotation
_UI_LAFScopeElement_lafElement_feature = Laf Element
